name: first workflow
on: workflow_dispatch
jobs:
  first_job:
  runs_on: ubuntu-latest
  steps:
   - name: print greeting
     run: echo"helloworld"
   - name: print goodbye
     run: echo "goodbye"
    
    
